// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Выравнено с остальным кодом (prisma.service.ts, seed.ts): принимаем любую из двух переменных.
    url: process.env['DATABASE_URL'] || process.env['POSTGRES_URL'],
  },
});
